name: Shell Scripts Unit Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v1
    - name: set it up
      run: |
        source setup
    - name: test it
      run: |
        direnv allow
